### ISSUE TITLE
Improve UI of Home Page

### ISSUE THREAD

**Issue by sanskaromar** [sanskaromar/todo-app#1]
Currently UI of Home Page of app is plain and simple. Use your creativity to improve it.

Keep in mind, we are looking for a minimalistic todo app, so try to keep it simple yet attractive.

**Comment by pranshuj73** [comment]
would like to take this up!

**Comment by sanskaromar** [comment]
@pranshuj73 Sure go ahead. 😃 
Please keep in touch with any ideas you come up with about UI before you start working.

**Comment by sanskaromar** [comment]
@pranshuj73 are you working on this? Any updates?

**Comment by pranshuj73** [comment]
Still on it,

https://dribbble.com/shots/18468605-Task-Management-App

I'lll be using this for the webpage design
