### ISSUE TITLE
Show count of tasks for each labels beside each labels tags on right hand side

### ISSUE THREAD

**Issue by sanskaromar** [sanskaromar/todo-app#15]
It should look something like this. You are open to make changes according to your creativity.

![Screenshot 2022-10-05 144943](https://user-images.githubusercontent.com/77530596/194027231-8637b8e2-3717-4ee3-ac1a-ebbebdc4ecb5.png)

**Comment by DevTMK** [comment]
@sanskaromar I would like to work on this

**Comment by sanskaromar** [comment]
Sure, go ahead.
