### ISSUE TITLE
Add feature for tasks to be able to add multiline tasks

### ISSUE THREAD

**Issue by sanskaromar** [sanskaromar/todo-app#2]
Currently, tasks are only single-lined. Add feature for tasks to be able to add multiline tasks.

**Comment by PriyavKaneria** [comment]
I will try this out too. Can I work on this?

**Comment by sanskaromar** [comment]
@PriyavKaneria Sure go ahead. 😄

**Comment by PriyavKaneria** [comment]
@sanskaromar Raised a PR can you please review it
