### ISSUE TITLE
Add a progress bar for ToDos

### ISSUE THREAD

**Issue by sanskaromar** [sanskaromar/todo-app#21]
- Add a progress bar for ToDos and show how many percent of them have been marked as done.
- Round off percentage to 0 decimals, i.e, 54.1 % should be shown as 54%, 69.9% should be shown as 69%, 70% should be shown as 70%.
- progress bar should be circular, and should look something like this on the right-hand side above the labels.
![image](https://user-images.githubusercontent.com/77530596/194223975-76af1f3b-edec-4e74-8b2c-221afe14a26e.png)

**Comment by manav-06** [comment]
Can you assign this to me @sanskaromar

**Comment by sanskaromar** [comment]
Sure, go agead @manav-06

**Comment by sanskaromar** [comment]
@manav-06 Are you still doing it?

**Comment by manav-06** [comment]
It'll be done by today. Sorry for the delay. Was busy in icpc work

**Comment by manav-06** [comment]
Hi, @sanskaromar should I keep it in bottom left. If the page is scrolled it doesn't cover any other component. But in top right it will go over the labels
![image](https://user-images.githubusercontent.com/56617785/194814308-e25e57fe-07ce-4e8f-a763-d8da2c1a917e.png)

**Comment by sanskaromar** [comment]
@manav-06 Yes, the bottom left would be fine 👍

**Comment by manav-06** [comment]
@sanskaromar please review #27

**Comment by sanskaromar** [comment]
@manav-06 Great Work 🔥
