### ISSUE TITLE
Design a logo for Track my Tasks

### ISSUE THREAD

**Issue by sanskaromar** [sanskaromar/todo-app#22]
Since the app is functional now with basic features *(and improving thanks to contributors like you)* we are now looking for a logo for our ToDo app - Track My Tasks.

Show your creativity and design a logo that represents the fact that it's a minimalistic ToDo App to clear your mental clutter.

Open for multiple people to take this up.

**Comment by kanishk6103** [comment]
can i give it a go?

**Comment by kanishk6103** [comment]
> Since the app is functional now with basic features _(and improving thanks to contributors like you)_ we are now looking for a logo for our ToDo app - Track My Tasks.
> 
> Show your creativity and design a logo that represents the fact that it's a minimalistic ToDo App to clear your mental clutter.

I have done some ideation for the logo

![image](https://user-images.githubusercontent.com/72643990/194242166-5b756b37-76b7-4ebc-9286-5d85a0e80374.png)

**Comment by sanskaromar** [comment]
> > Since the app is functional now with basic features _(and improving thanks to contributors like you)_ we are now looking for a logo for our ToDo app - Track My Tasks.
> > Show your creativity and design a logo that represents the fact that it's a minimalistic ToDo App to clear your mental clutter.
> 
> I have done some ideation for the logo
> 
> ![image](https://user-images.githubusercontent.com/72643990/194242166-5b756b37-76b7-4ebc-9286-5d85a0e80374.png)

This idea really is clean and I like this. I want to ask though, since the app currently is named Track my tasks. Can we do something about that.
Also, my other concern is that won't the text ToDo look proportionally very small? I think without any text this might look better. 

Anyways, go ahead with whatever you think is best. 🚀

**Comment by kanishk6103** [comment]
> > > Since the app is functional now with basic features _(and improving thanks to contributors like you)_ we are now looking for a logo for our ToDo app - Track My Tasks.
> > > Show your creativity and design a logo that represents the fact that it's a minimalistic ToDo App to clear your mental clutter.
> > 
> > 
> > I have done some ideation for the logo
> > ![image](https://user-images.githubusercontent.com/72643990/194242166-5b756b37-76b7-4ebc-9286-5d85a0e80374.png)
> 
> This idea really is clean and I like this. I want to ask though, since the app currently is named Track my tasks. Can we do something about that. Also, my other concern is that won't the text ToDo look proportionally very small? I think without any text this might look better.
> 
> Anyways, go ahead with whatever you think is best. 🚀

sure sure, this was just to tell you how the logo could possibly look like, i'll do the required changes

**Comment by sanskaromar** [comment]
@kanishk6103 Something bluish would be great. Like the background color of dark theme. And if you need light colors for something, probably light theme's background, or anything that looks good. it's flexible.

**Comment by kanishk6103** [comment]
> @kanishk6103 Something bluish would be great. Like the background color of dark theme. And if you need light colors for something, probably light theme's background, or anything that looks good. it's flexible.

![image](https://user-images.githubusercontent.com/72643990/194304607-4a090e39-31d8-4431-af0a-cd26a5ac6625.png)

how'd this look?

**Comment by kanishk6103** [comment]
![image](https://user-images.githubusercontent.com/72643990/194368734-dcd87f95-a7b3-457b-8f20-e6d23083d270.png)
 
Is this better?

**Comment by sanskaromar** [comment]
@kanishk6103 Last one seems great. 🚀

**Comment by kanishk6103** [comment]
> @kanishk6103 Last one seems great. 🚀

glad you like it!
How do i send you? Do i send you the svg code?

**Comment by sanskaromar** [comment]
@kanishk6103 
You can email me and you can raise a PR and replace the temporary logo in `/src/assets/`

Also, can you work on a favicon for the same? You can replace `favicon.ico` with `/public/favicon.ico`

**Comment by kanishk6103** [comment]
> @kanishk6103 You can email me and you can raise a PR and replace the temporary logo in `/src/assets/`
> 
> Also, can you work on a favicon for the same? You can replace `favicon.ico` with `/public/favicon.ico`

Done! sent favicon and logo zips to your email.

**Comment by kanishk6103** [comment]
> @kanishk6103 You can email me and you can raise a PR and replace the temporary logo in `/src/assets/`
> 
> Also, can you work on a favicon for the same? You can replace `favicon.ico` with `/public/favicon.ico`

also sent a PR, kindly merge it.

**Comment by sanskaromar** [comment]
Thank you @kanishk6103

**Comment by kanishk6103** [comment]
> Thank you @kanishk6103 
> I have merged the PR.

Thx :D

If you want something improved in the logo, you can contact me
