### ISSUE TITLE
Improve UI of /todo route

### ISSUE THREAD

**Issue by sanskaromar** [sanskaromar/todo-app#3]
Improve UI of /todo route according to UI of the home page to match the theme.

THIS ISSUE DEPENDS UPON ISSUE #1. Please resolve that first.

**Comment by amitmishra11** [comment]
@sanskaromar can I work on this?
as someone is already working on 1

**Comment by sanskaromar** [comment]
Sure you can go ahead. Please discuss any changes you would like to make.

**Comment by amitmishra11** [comment]
@sanskaromar  The changes I am looking to make are:
1. Add good hover effects with proper color pallete wherever required
2. The task boxes height can be increased along with the font size which would look better than current state.
3. Other minor changes as applicable.

**Comment by sanskaromar** [comment]
@amitmishra11 That's great. Please go ahead.
