### ISSUE TITLE
Implement dark theme

### ISSUE THREAD

**Issue by sanskaromar** [sanskaromar/todo-app#4]

**Comment by PriyavKaneria** [comment]
I can implement this. Can you assign this issue to me?

**Comment by sanskaromar** [comment]
Sure. I'll assign you once you are done with #2

**Comment by amitmishra11** [comment]
@sanskaromar can I work on this?

**Comment by sanskaromar** [comment]
@amitmishra11 This issue depends upon #3 and hence upon #1 as I would like to keep UI consistent. Until that is done, please find some other features that you can contribute to and make mention in an issue.

**Comment by adityaa22** [comment]
I have an easy and neat implementation for this. Can You please assign me this issue?
