### ISSUE TITLE
Allow users to be able to add labels to tasks

### ISSUE THREAD

**Issue by sanskaromar** [sanskaromar/todo-app#6]
Currently, Tasks are plain and simple textboxes. Allow, users to be able to add labels to them.

**Comment by PriyavKaneria** [comment]
I'll work on this after #5  as we discussed in email 😇

**Comment by PriyavKaneria** [comment]
Should the labels be pre defined? Also, will the user be able to add custom labels?

**Comment by sanskaromar** [comment]
@PriyavKaneria We can start off with a few predefined labels. Then later we can allow users to customize them.

**Comment by PriyavKaneria** [comment]
@sanskaromar Raised a PR for the Labels with UI as we discussed on email
