### ISSUE TITLE
Allow users to be able to sign out and clear the list

### ISSUE THREAD

**Issue by adityaa22** [sanskaromar/todo-app#9]
I feel following features could be implemented to make the UI look good
- a Sign Out option available to the users 
-  a feature to clear the list at once

**Comment by sanskaromar** [comment]
@adityaa22 Sure, would you like to do this?

**Comment by adityaa22** [comment]
Yes, I have made these small changes in my branch. Can you please assign this to me.

**Comment by sanskaromar** [comment]
Raise a PR when you are done with changes. 🥳
